{% set name = "jupyterlab-nvdashboard" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3a9d1e7142b700fb51bffdab5935ba1d4a8a824fdd5b09540a3c2a76a5e1a961

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - nodejs
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0
  run:
    - python >={{ python_min }}
    - jupyterlab >=4
    - psutil
    - pynvml >=12.0.0,<13.0.0a0

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - jupyterlab_nvdashboard

about:
  home: https://rapids.ai
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A JupyterLab extension for displaying dashboards of GPU usage
  description: |
    A JupyterLab extension for displaying dashboards of GPU usage.
  doc_url: https://github.com/rapidsai/jupyterlab-nvdashboard
  dev_url: https://github.com/rapidsai/jupyterlab-nvdashboard

extra:
  recipe-maintainers:
    - jacobtomlinson
    - rjzamora
    - owenlamont
    - AjayThorve
