{% set name = "jupyterlab-nvdashboard" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6345a696ad9641a20a3c579a1a9bc44caf0cb6090ae7b914e2c8de33dbe6b3d2

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - pynvml
    - psutil
    - nodejs
    - jupyter-packaging >=0.7.0,<0.8
    - jupyterlab >=3.0.0,<4
  run:
    - python >=3.7
    - jupyterlab >=3.0.0,<4
    - jupyter-server-proxy >=1.3.2
    - bokeh >2.1
    - pynvml
    - psutil

test:
  imports:
    - jupyterlab_nvdashboard

about:
  home: https://rapids.ai
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A JupyterLab extension for displaying dashboards of GPU usage
  description: |
    A JupyterLab extension for displaying dashboards of GPU usage.
  doc_url: https://github.com/rapidsai/jupyterlab-nvdashboard
  dev_url: https://github.com/rapidsai/jupyterlab-nvdashboard

extra:
  recipe-maintainers:
    - jacobtomlinson
    - rjzamora
    - owenlamont
