{% set name = "jupyterlab-nvdashboard" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3a9d1e7142b700fb51bffdab5935ba1d4a8a824fdd5b09540a3c2a76a5e1a961

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - hatchling >=1.5.0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - pynvml
    - psutil
    - nodejs
    - jupyter-packaging
    - jupyterlab >=4
  run:
    - python >=3.8
    - jupyterlab >=4
    - pynvml
    - psutil

test:
  imports:
    - jupyterlab_nvdashboard

about:
  home: https://rapids.ai
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A JupyterLab extension for displaying dashboards of GPU usage
  description: |
    A JupyterLab extension for displaying dashboards of GPU usage.
  doc_url: https://github.com/rapidsai/jupyterlab-nvdashboard
  dev_url: https://github.com/rapidsai/jupyterlab-nvdashboard

extra:
  recipe-maintainers:
    - jacobtomlinson
    - rjzamora
    - owenlamont
    - AjayThorve
