{% set name = "jupyterlab-nvdashboard" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 829ba559d937ac67331eacffe04fc63b6226a9b238f0fa6fdd42efa9979cf3a2

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
    - jupyter labextension install jupyterlab-nvdashboard@v{{ version }}
    - jupyter lab build

requirements:
  host:
    - python >=3.5
    - pip
    - jupyterlab >=1.0
    - nodejs
  run:
    - python >=3.5
    - jupyter-server-proxy
    - bokeh
    - pynvml
    - psutil
    - nodejs

test:
  imports:
    - jupyterlab_nvdashboard

about:
  home: https://github.com/rapidsai/jupyterlab-nvdashboard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A JupyterLab extension for displaying dashboards of GPU usage'
  description: |
    A JupyterLab extension for displaying dashboards of GPU usage.
  doc_url: https://github.com/rapidsai/jupyterlab-nvdashboard
  dev_url: https://github.com/rapidsai/jupyterlab-nvdashboard

extra:
  recipe-maintainers:
    - jacobtomlinson
    - rjzamora
