{% set name = "jupyterlab-nvdashboard" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rapidsai/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fdc2739627eb1047c6b2df35045b654e07924fc9f6f8d490a34967365e75fd60

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.5.0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - nodejs
    - jupyter-packaging
    - jupyterlab >=4
  run:
    - python >={{ python_min }}
    - jupyterlab >=4
    - pynvml >=11.0.0,<12.0.0a0
    - psutil

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - jupyterlab_nvdashboard

about:
  home: https://rapids.ai
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A JupyterLab extension for displaying dashboards of GPU usage
  description: |
    A JupyterLab extension for displaying dashboards of GPU usage.
  doc_url: https://github.com/rapidsai/jupyterlab-nvdashboard
  dev_url: https://github.com/rapidsai/jupyterlab-nvdashboard

extra:
  recipe-maintainers:
    - jacobtomlinson
    - rjzamora
    - owenlamont
    - AjayThorve
